language: php

php:
- '7.0'
- '5.6'
- '5.5'
- '5.4'
- '5.3'

cache:
  directories:
    - .cache

# travis cache does not support files, only directories
# so do some hackery to use .cache/ for caching box.phar between builds
before_script: |
  if [ -e .cache/box.phar ]; then
    cp -p .cache/box.phar .
  else
    make box.phar
    cp -p box.phar .cache
  fi

script:
  - make phar

# https://docs.travis-ci.com/user/deployment/releases
deploy:
  provider: releases
  api_key:
    secure: x3bCH29HQm6R/NLnLbjh63B9W9oIWzMNg3R8LdBVj8mFwyjNePKJ13jmXiX4OdrGk9qofr0F5RM4nw18vHt44IXXX5rCaTpky53PWjrWNYhwKhhuThZKMctTlcTlptT3FKr6Gln2y9qYMEGDAQmZ/w6dv7YMelp2d1P64XSyxOY=
  file:
    - eventum-cvs-hook.phar
    - eventum-git-hook.phar
    - eventum-svn-hook.phar
  skip_cleanup: true
  on:
    repo: eventum/scm
    tags: true

# vim:ft=yaml:et:ts=2:sw=2
