language: php
dist: trusty

jobs:
  fast_finish: true
  allow_failures:
    - php: "hhvm"
  include:
    - php: "5.3"
      dist: precise
    - php: "5.4"
    - php: "5.5"
    - php: "5.6"
    - php: "7.0"
    - php: "7.1"
    - php: "7.2"
    - php: "7.3"
    - php: "7.4snapshot"
    - php: "nightly"

cache:
  directories:
    - .cache

# travis cache does not support files, only directories
# so do some hackery to use .cache/ for caching box.phar between builds
before_script: |
  if [ -e .cache/box.phar ]; then
    cp -p .cache/box.phar .
  else
    make box.phar
    cp -p box.phar .cache
  fi

script:
  - make phar

deploy:
  provider: releases
  # https://docs.travis-ci.com/user/deployment/releases/
  # Create token with privilege in https://github.com/settings/tokens and set as env var.
  # It must have the public_repo or repo scope to upload assets
  # $ travis env set -p GITHUB_API_TOKEN abcdefabcdefabcdef
  # or via https://travis-ci.org/eventum/scm/settings
  # or automate all with:
  # $ travis setup releases
  api_key: $GITHUB_API_TOKEN
  file:
    - eventum-cvs-hook.phar
    - eventum-git-hook.phar
    - eventum-svn-hook.phar
  skip_cleanup: true
  on:
    repo: eventum/scm
    php: '5.6'
    tags: true

# vim:ft=yaml:et:ts=2:sw=2
