language: php

php:
- '7.0'
- '5.6'
- '5.5'
- '5.4'
- '5.3'

cache:
  directories:
    - .cache

# travis cache does not support files, only directories
# so do some hackery to use .cache/ for caching box.phar between builds
before_script: |
  if [ -e .cache/box.phar ]; then
    cp -p .cache/box.phar .
  else
    make box.phar
    cp -p box.phar .cache
  fi

script:
  - make phar

# vim:ft=yaml:et:ts=2:sw=2
